### ISSUE TITLE
run functions arent being passed restart as a bool

### ISSUE THREAD

**Issue by mmelo-yottaa** [dns-groot/Ferret#1]
thanks for sharing this code, interesting!  

I think DifferentialTesting/Implementations/main.py line 112-113  wants to pass the value False and not the string "False" to the run function...  seems despite your annotations mypy flag find this issue because of the indirect call through globals dict...

**Comment by SivaKesava1** [comment]
Thanks for filing the issue. I just checked the `main.py` with mypy as `python3 -m mypy main.py` and ignored the "did not find module error" for all the imports, and `mypy` assumed it as `Any` type. Therefore, this one slipped.
